FROM ubuntu:16.04

RUN echo "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse" >> /etc/apt/sources.list && \
    apt-get -qq update  && \
    apt-get install -y cmake \
                       curl
RUN curl -sL curl -sL https://deb.nodesource.com/setup_8.x | bash

RUN apt-get -y install nodejs

RUN apt-get -y install build-essential

COPY package*.json ./
COPY requirements.txt ./

RUN npm install

# COPY . .

# EXPOSE 8080
# CMD ['npm','start']
