FROM ubuntu:16.04

RUN echo "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse" >> /etc/apt/sources.list && \
    apt-get -qq update  && \
    apt-get install -y cmake \
                       curl

RUN curl -sL curl -sL https://deb.nodesource.com/setup_8.x | bash

RUN apt-get -y install nodejs

RUN apt-get -y install build-essential  \
                       wget\
                       unzip\
                       git  \
                # installing dependency for python
                       python-opengl \
                       xorg-dev \
                       python3-dev \
                       python3-pip  \
                       swig3.0 \
                       libopenblas-dev \
                       liblapack-dev \
                       libsdl2-dev \
                       libboost-all-dev \
                       graphviz \
                       gcc \
                # dependency for openCV
                       pkg-config \
                       libswscale-dev \
                       libtbb2 \
                       libtbb-dev \
                       yasm \
                       libjpeg-dev \
                       libpng-dev \
                       libtiff-dev \
                       libavformat-dev \
                       libpq-dev \
                       g++ && \
    ln -s /usr/bin/swig3.0 /usr/bin/swig

RUN apt-get -y install

# cloning  he openCV
# ENV OPENCV_VERSION="4.0.0"
# RUN wget https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip

# unzip and build openCV
# RUN unzip ${OPENCV_VERSION}.zip \
#     && mkdir /opencv-${OPENCV_VERSION}/cmake_binary \
#     && cd /opencv-${OPENCV_VERSION}/cmake_binary \
#     && cmake -DBUILD_TIFF=ON \
#     -DBUILD_opencv_java=OFF \
#     -DWITH_CUDA=OFF \
#     -DWITH_OPENGL=ON \
#     -DWITH_OPENCL=ON \
#     -DWITH_IPP=ON \
#     -DWITH_TBB=ON \
#     -DWITH_EIGEN=ON \
#     -DWITH_V4L=ON \
#     -DBUILD_TESTS=OFF \
#     -DBUILD_PERF_TESTS=OFF \
#     -DCMAKE_BUILD_TYPE=RELEASE \
#     -DCMAKE_INSTALL_PREFIX=$(python3 -c "import sys; print(sys.prefix)") \
#     -DPYTHON_EXECUTABLE=$(which python3) \
#     -DPYTHON_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") \
#     -DPYTHON_PACKAGES_PATH=$(python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") \

# RUN cd /opencv-${OPENCV_VERSION}/ \
#     && make -j 10 install \
#     && rm /${OPENCV_VERSION}.zip \
#     && rm -r /opencv-${OPENCV_VERSION}

# RUN ln -s \
#   /usr/local/python3/cv2/python-3.5/cv2.cpython-37m-x86_64-linux-gnu.so \
#   /usr/local/lib/python3.5/site-packages/cv2.so

COPY package*.json ./
COPY requirements.txt ./

RUN npm install

# COPY . .

# EXPOSE 8080
# CMD ['npm','start']
